//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopRecord", Namespace="http://tempuri.org/")]
    public partial class ShopRecord : object
    {
        
        private string IdField;
        
        private System.DateTime TimeField;
        
        private double SumField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Sum
        {
            get
            {
                return this.SumField;
            }
            set
            {
                this.SumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    public partial class Product : object
    {
        
        private string IdField;
        
        private string NameField;
        
        private string DescriptionField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ServiceReference1.HelloWorldResponse HelloWorld(ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.HelloWorldResponse> HelloWorldAsync(ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 name 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateProduct", ReplyAction="*")]
        ServiceReference1.CreateProductResponse CreateProduct(ServiceReference1.CreateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CreateProductResponse> CreateProductAsync(ServiceReference1.CreateProductRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 id 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        ServiceReference1.EditResponse Edit(ServiceReference1.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.EditResponse> EditAsync(ServiceReference1.EditRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 id 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        ServiceReference1.DeleteProductResponse DeleteProduct(ServiceReference1.DeleteProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.DeleteProductResponse> DeleteProductAsync(ServiceReference1.DeleteProductRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 GetShopRecordsResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShopRecords", ReplyAction="*")]
        ServiceReference1.GetShopRecordsResponse GetShopRecords(ServiceReference1.GetShopRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShopRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetShopRecordsResponse> GetShopRecordsAsync(ServiceReference1.GetShopRecordsRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 ShowAllProductsResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllProducts", ReplyAction="*")]
        ServiceReference1.ShowAllProductsResponse ShowAllProducts(ServiceReference1.ShowAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ShowAllProductsResponse> ShowAllProductsAsync(ServiceReference1.ShowAllProductsRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 id 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        ServiceReference1.FindResponse Find(ServiceReference1.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.FindResponse> FindAsync(ServiceReference1.FindRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(ServiceReference1.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(ServiceReference1.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProductRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProduct", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CreateProductRequestBody Body;
        
        public CreateProductRequest()
        {
        }
        
        public CreateProductRequest(ServiceReference1.CreateProductRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateProductRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double price;
        
        public CreateProductRequestBody()
        {
        }
        
        public CreateProductRequestBody(string name, string description, double price)
        {
            this.name = name;
            this.description = description;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProductResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CreateProductResponseBody Body;
        
        public CreateProductResponse()
        {
        }
        
        public CreateProductResponse(ServiceReference1.CreateProductResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateProductResponseBody
    {
        
        public CreateProductResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.EditRequestBody Body;
        
        public EditRequest()
        {
        }
        
        public EditRequest(ServiceReference1.EditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double price;
        
        public EditRequestBody()
        {
        }
        
        public EditRequestBody(string id, string name, string description, double price)
        {
            this.id = id;
            this.name = name;
            this.description = description;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.EditResponseBody Body;
        
        public EditResponse()
        {
        }
        
        public EditResponse(ServiceReference1.EditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditResponseBody
    {
        
        public EditResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProduct", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DeleteProductRequestBody Body;
        
        public DeleteProductRequest()
        {
        }
        
        public DeleteProductRequest(ServiceReference1.DeleteProductRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteProductRequestBody()
        {
        }
        
        public DeleteProductRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.DeleteProductResponseBody Body;
        
        public DeleteProductResponse()
        {
        }
        
        public DeleteProductResponse(ServiceReference1.DeleteProductResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteProductResult;
        
        public DeleteProductResponseBody()
        {
        }
        
        public DeleteProductResponseBody(int DeleteProductResult)
        {
            this.DeleteProductResult = DeleteProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShopRecordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShopRecords", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetShopRecordsRequestBody Body;
        
        public GetShopRecordsRequest()
        {
        }
        
        public GetShopRecordsRequest(ServiceReference1.GetShopRecordsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetShopRecordsRequestBody
    {
        
        public GetShopRecordsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShopRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShopRecordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetShopRecordsResponseBody Body;
        
        public GetShopRecordsResponse()
        {
        }
        
        public GetShopRecordsResponse(ServiceReference1.GetShopRecordsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetShopRecordsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ShopRecord[] GetShopRecordsResult;
        
        public GetShopRecordsResponseBody()
        {
        }
        
        public GetShopRecordsResponseBody(ServiceReference1.ShopRecord[] GetShopRecordsResult)
        {
            this.GetShopRecordsResult = GetShopRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ShowAllProductsRequestBody Body;
        
        public ShowAllProductsRequest()
        {
        }
        
        public ShowAllProductsRequest(ServiceReference1.ShowAllProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowAllProductsRequestBody
    {
        
        public ShowAllProductsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ShowAllProductsResponseBody Body;
        
        public ShowAllProductsResponse()
        {
        }
        
        public ShowAllProductsResponse(ServiceReference1.ShowAllProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowAllProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Product[] ShowAllProductsResult;
        
        public ShowAllProductsResponseBody()
        {
        }
        
        public ShowAllProductsResponseBody(ServiceReference1.Product[] ShowAllProductsResult)
        {
            this.ShowAllProductsResult = ShowAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.FindRequestBody Body;
        
        public FindRequest()
        {
        }
        
        public FindRequest(ServiceReference1.FindRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public FindRequestBody()
        {
        }
        
        public FindRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.FindResponseBody Body;
        
        public FindResponse()
        {
        }
        
        public FindResponse(ServiceReference1.FindResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Product FindResult;
        
        public FindResponseBody()
        {
        }
        
        public FindResponseBody(ServiceReference1.Product FindResult)
        {
            this.FindResult = FindResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebService1SoapChannel : ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebService1Soap>, ServiceReference1.WebService1Soap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.HelloWorldResponse ServiceReference1.WebService1Soap.HelloWorld(ServiceReference1.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld()
        {
            ServiceReference1.HelloWorldRequest inValue = new ServiceReference1.HelloWorldRequest();
            inValue.Body = new ServiceReference1.HelloWorldRequestBody();
            ServiceReference1.HelloWorldResponse retVal = ((ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.HelloWorldResponse> ServiceReference1.WebService1Soap.HelloWorldAsync(ServiceReference1.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.HelloWorldResponse> HelloWorldAsync()
        {
            ServiceReference1.HelloWorldRequest inValue = new ServiceReference1.HelloWorldRequest();
            inValue.Body = new ServiceReference1.HelloWorldRequestBody();
            return ((ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.CreateProductResponse ServiceReference1.WebService1Soap.CreateProduct(ServiceReference1.CreateProductRequest request)
        {
            return base.Channel.CreateProduct(request);
        }
        
        public void CreateProduct(string name, string description, double price)
        {
            ServiceReference1.CreateProductRequest inValue = new ServiceReference1.CreateProductRequest();
            inValue.Body = new ServiceReference1.CreateProductRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            ServiceReference1.CreateProductResponse retVal = ((ServiceReference1.WebService1Soap)(this)).CreateProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreateProductResponse> ServiceReference1.WebService1Soap.CreateProductAsync(ServiceReference1.CreateProductRequest request)
        {
            return base.Channel.CreateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateProductResponse> CreateProductAsync(string name, string description, double price)
        {
            ServiceReference1.CreateProductRequest inValue = new ServiceReference1.CreateProductRequest();
            inValue.Body = new ServiceReference1.CreateProductRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            return ((ServiceReference1.WebService1Soap)(this)).CreateProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.EditResponse ServiceReference1.WebService1Soap.Edit(ServiceReference1.EditRequest request)
        {
            return base.Channel.Edit(request);
        }
        
        public void Edit(string id, string name, string description, double price)
        {
            ServiceReference1.EditRequest inValue = new ServiceReference1.EditRequest();
            inValue.Body = new ServiceReference1.EditRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            ServiceReference1.EditResponse retVal = ((ServiceReference1.WebService1Soap)(this)).Edit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.EditResponse> ServiceReference1.WebService1Soap.EditAsync(ServiceReference1.EditRequest request)
        {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EditResponse> EditAsync(string id, string name, string description, double price)
        {
            ServiceReference1.EditRequest inValue = new ServiceReference1.EditRequest();
            inValue.Body = new ServiceReference1.EditRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.price = price;
            return ((ServiceReference1.WebService1Soap)(this)).EditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DeleteProductResponse ServiceReference1.WebService1Soap.DeleteProduct(ServiceReference1.DeleteProductRequest request)
        {
            return base.Channel.DeleteProduct(request);
        }
        
        public int DeleteProduct(string id)
        {
            ServiceReference1.DeleteProductRequest inValue = new ServiceReference1.DeleteProductRequest();
            inValue.Body = new ServiceReference1.DeleteProductRequestBody();
            inValue.Body.id = id;
            ServiceReference1.DeleteProductResponse retVal = ((ServiceReference1.WebService1Soap)(this)).DeleteProduct(inValue);
            return retVal.Body.DeleteProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DeleteProductResponse> ServiceReference1.WebService1Soap.DeleteProductAsync(ServiceReference1.DeleteProductRequest request)
        {
            return base.Channel.DeleteProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DeleteProductResponse> DeleteProductAsync(string id)
        {
            ServiceReference1.DeleteProductRequest inValue = new ServiceReference1.DeleteProductRequest();
            inValue.Body = new ServiceReference1.DeleteProductRequestBody();
            inValue.Body.id = id;
            return ((ServiceReference1.WebService1Soap)(this)).DeleteProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetShopRecordsResponse ServiceReference1.WebService1Soap.GetShopRecords(ServiceReference1.GetShopRecordsRequest request)
        {
            return base.Channel.GetShopRecords(request);
        }
        
        public ServiceReference1.ShopRecord[] GetShopRecords()
        {
            ServiceReference1.GetShopRecordsRequest inValue = new ServiceReference1.GetShopRecordsRequest();
            inValue.Body = new ServiceReference1.GetShopRecordsRequestBody();
            ServiceReference1.GetShopRecordsResponse retVal = ((ServiceReference1.WebService1Soap)(this)).GetShopRecords(inValue);
            return retVal.Body.GetShopRecordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetShopRecordsResponse> ServiceReference1.WebService1Soap.GetShopRecordsAsync(ServiceReference1.GetShopRecordsRequest request)
        {
            return base.Channel.GetShopRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetShopRecordsResponse> GetShopRecordsAsync()
        {
            ServiceReference1.GetShopRecordsRequest inValue = new ServiceReference1.GetShopRecordsRequest();
            inValue.Body = new ServiceReference1.GetShopRecordsRequestBody();
            return ((ServiceReference1.WebService1Soap)(this)).GetShopRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.ShowAllProductsResponse ServiceReference1.WebService1Soap.ShowAllProducts(ServiceReference1.ShowAllProductsRequest request)
        {
            return base.Channel.ShowAllProducts(request);
        }
        
        public ServiceReference1.Product[] ShowAllProducts()
        {
            ServiceReference1.ShowAllProductsRequest inValue = new ServiceReference1.ShowAllProductsRequest();
            inValue.Body = new ServiceReference1.ShowAllProductsRequestBody();
            ServiceReference1.ShowAllProductsResponse retVal = ((ServiceReference1.WebService1Soap)(this)).ShowAllProducts(inValue);
            return retVal.Body.ShowAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ShowAllProductsResponse> ServiceReference1.WebService1Soap.ShowAllProductsAsync(ServiceReference1.ShowAllProductsRequest request)
        {
            return base.Channel.ShowAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ShowAllProductsResponse> ShowAllProductsAsync()
        {
            ServiceReference1.ShowAllProductsRequest inValue = new ServiceReference1.ShowAllProductsRequest();
            inValue.Body = new ServiceReference1.ShowAllProductsRequestBody();
            return ((ServiceReference1.WebService1Soap)(this)).ShowAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.FindResponse ServiceReference1.WebService1Soap.Find(ServiceReference1.FindRequest request)
        {
            return base.Channel.Find(request);
        }
        
        public ServiceReference1.Product Find(string id)
        {
            ServiceReference1.FindRequest inValue = new ServiceReference1.FindRequest();
            inValue.Body = new ServiceReference1.FindRequestBody();
            inValue.Body.id = id;
            ServiceReference1.FindResponse retVal = ((ServiceReference1.WebService1Soap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.FindResponse> ServiceReference1.WebService1Soap.FindAsync(ServiceReference1.FindRequest request)
        {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FindResponse> FindAsync(string id)
        {
            ServiceReference1.FindRequest inValue = new ServiceReference1.FindRequest();
            inValue.Body = new ServiceReference1.FindRequestBody();
            inValue.Body.id = id;
            return ((ServiceReference1.WebService1Soap)(this)).FindAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:65225/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:65225/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
