//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    public partial class Product : object
    {
        
        private string IdField;
        
        private string NameField;
        
        private string DescriptionField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectedProduct", Namespace="http://tempuri.org/")]
    public partial class SelectedProduct : object
    {
        
        private string IdField;
        
        private string NameField;
        
        private double PriceField;
        
        private int numField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int num
        {
            get
            {
                return this.numField;
            }
            set
            {
                this.numField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceClient.WebService2Soap")]
    public interface WebService2Soap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ServiceReferenceClient.HelloWorldResponse HelloWorld(ServiceReferenceClient.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient.HelloWorldResponse> HelloWorldAsync(ServiceReferenceClient.HelloWorldRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 GetProductListResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductList", ReplyAction="*")]
        ServiceReferenceClient.GetProductListResponse GetProductList(ServiceReferenceClient.GetProductListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient.GetProductListResponse> GetProductListAsync(ServiceReferenceClient.GetProductListRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 id 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProductToShoppingList", ReplyAction="*")]
        ServiceReferenceClient.AddProductToShoppingListResponse AddProductToShoppingList(ServiceReferenceClient.AddProductToShoppingListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProductToShoppingList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient.AddProductToShoppingListResponse> AddProductToShoppingListAsync(ServiceReferenceClient.AddProductToShoppingListRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 FinishShoppingResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishShopping", ReplyAction="*")]
        ServiceReferenceClient.FinishShoppingResponse FinishShopping(ServiceReferenceClient.FinishShoppingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishShopping", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient.FinishShoppingResponse> FinishShoppingAsync(ServiceReferenceClient.FinishShoppingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccount", ReplyAction="*")]
        double GetAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNum", ReplyAction="*")]
        int GetNum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetNumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearShoppingList", ReplyAction="*")]
        void ClearShoppingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearShoppingList", ReplyAction="*")]
        System.Threading.Tasks.Task ClearShoppingListAsync();
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 ShowSelectedProductsResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSelectedProducts", ReplyAction="*")]
        ServiceReferenceClient.ShowSelectedProductsResponse ShowSelectedProducts(ServiceReferenceClient.ShowSelectedProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSelectedProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient.ShowSelectedProductsResponse> ShowSelectedProductsAsync(ServiceReferenceClient.ShowSelectedProductsRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 id 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveSelected", ReplyAction="*")]
        ServiceReferenceClient.RemoveSelectedResponse RemoveSelected(ServiceReferenceClient.RemoveSelectedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveSelected", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceClient.RemoveSelectedResponse> RemoveSelectedAsync(ServiceReferenceClient.RemoveSelectedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(ServiceReferenceClient.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(ServiceReferenceClient.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductList", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.GetProductListRequestBody Body;
        
        public GetProductListRequest()
        {
        }
        
        public GetProductListRequest(ServiceReferenceClient.GetProductListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductListRequestBody
    {
        
        public GetProductListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.GetProductListResponseBody Body;
        
        public GetProductListResponse()
        {
        }
        
        public GetProductListResponse(ServiceReferenceClient.GetProductListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceClient.Product[] GetProductListResult;
        
        public GetProductListResponseBody()
        {
        }
        
        public GetProductListResponseBody(ServiceReferenceClient.Product[] GetProductListResult)
        {
            this.GetProductListResult = GetProductListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductToShoppingListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductToShoppingList", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.AddProductToShoppingListRequestBody Body;
        
        public AddProductToShoppingListRequest()
        {
        }
        
        public AddProductToShoppingListRequest(ServiceReferenceClient.AddProductToShoppingListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductToShoppingListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public AddProductToShoppingListRequestBody()
        {
        }
        
        public AddProductToShoppingListRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductToShoppingListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductToShoppingListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.AddProductToShoppingListResponseBody Body;
        
        public AddProductToShoppingListResponse()
        {
        }
        
        public AddProductToShoppingListResponse(ServiceReferenceClient.AddProductToShoppingListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddProductToShoppingListResponseBody
    {
        
        public AddProductToShoppingListResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinishShoppingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinishShopping", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.FinishShoppingRequestBody Body;
        
        public FinishShoppingRequest()
        {
        }
        
        public FinishShoppingRequest(ServiceReferenceClient.FinishShoppingRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FinishShoppingRequestBody
    {
        
        public FinishShoppingRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinishShoppingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinishShoppingResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.FinishShoppingResponseBody Body;
        
        public FinishShoppingResponse()
        {
        }
        
        public FinishShoppingResponse(ServiceReferenceClient.FinishShoppingResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FinishShoppingResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceClient.SelectedProduct[] FinishShoppingResult;
        
        public FinishShoppingResponseBody()
        {
        }
        
        public FinishShoppingResponseBody(ServiceReferenceClient.SelectedProduct[] FinishShoppingResult)
        {
            this.FinishShoppingResult = FinishShoppingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowSelectedProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowSelectedProducts", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.ShowSelectedProductsRequestBody Body;
        
        public ShowSelectedProductsRequest()
        {
        }
        
        public ShowSelectedProductsRequest(ServiceReferenceClient.ShowSelectedProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowSelectedProductsRequestBody
    {
        
        public ShowSelectedProductsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowSelectedProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowSelectedProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.ShowSelectedProductsResponseBody Body;
        
        public ShowSelectedProductsResponse()
        {
        }
        
        public ShowSelectedProductsResponse(ServiceReferenceClient.ShowSelectedProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowSelectedProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceClient.SelectedProduct[] ShowSelectedProductsResult;
        
        public ShowSelectedProductsResponseBody()
        {
        }
        
        public ShowSelectedProductsResponseBody(ServiceReferenceClient.SelectedProduct[] ShowSelectedProductsResult)
        {
            this.ShowSelectedProductsResult = ShowSelectedProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveSelectedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveSelected", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.RemoveSelectedRequestBody Body;
        
        public RemoveSelectedRequest()
        {
        }
        
        public RemoveSelectedRequest(ServiceReferenceClient.RemoveSelectedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveSelectedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public RemoveSelectedRequestBody()
        {
        }
        
        public RemoveSelectedRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveSelectedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveSelectedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceClient.RemoveSelectedResponseBody Body;
        
        public RemoveSelectedResponse()
        {
        }
        
        public RemoveSelectedResponse(ServiceReferenceClient.RemoveSelectedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemoveSelectedResponseBody
    {
        
        public RemoveSelectedResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebService2SoapChannel : ServiceReferenceClient.WebService2Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<ServiceReferenceClient.WebService2Soap>, ServiceReferenceClient.WebService2Soap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService2SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService2SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService2SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService2SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService2SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService2SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService2SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient.HelloWorldResponse ServiceReferenceClient.WebService2Soap.HelloWorld(ServiceReferenceClient.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld()
        {
            ServiceReferenceClient.HelloWorldRequest inValue = new ServiceReferenceClient.HelloWorldRequest();
            inValue.Body = new ServiceReferenceClient.HelloWorldRequestBody();
            ServiceReferenceClient.HelloWorldResponse retVal = ((ServiceReferenceClient.WebService2Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient.HelloWorldResponse> ServiceReferenceClient.WebService2Soap.HelloWorldAsync(ServiceReferenceClient.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient.HelloWorldResponse> HelloWorldAsync()
        {
            ServiceReferenceClient.HelloWorldRequest inValue = new ServiceReferenceClient.HelloWorldRequest();
            inValue.Body = new ServiceReferenceClient.HelloWorldRequestBody();
            return ((ServiceReferenceClient.WebService2Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient.GetProductListResponse ServiceReferenceClient.WebService2Soap.GetProductList(ServiceReferenceClient.GetProductListRequest request)
        {
            return base.Channel.GetProductList(request);
        }
        
        public ServiceReferenceClient.Product[] GetProductList()
        {
            ServiceReferenceClient.GetProductListRequest inValue = new ServiceReferenceClient.GetProductListRequest();
            inValue.Body = new ServiceReferenceClient.GetProductListRequestBody();
            ServiceReferenceClient.GetProductListResponse retVal = ((ServiceReferenceClient.WebService2Soap)(this)).GetProductList(inValue);
            return retVal.Body.GetProductListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient.GetProductListResponse> ServiceReferenceClient.WebService2Soap.GetProductListAsync(ServiceReferenceClient.GetProductListRequest request)
        {
            return base.Channel.GetProductListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient.GetProductListResponse> GetProductListAsync()
        {
            ServiceReferenceClient.GetProductListRequest inValue = new ServiceReferenceClient.GetProductListRequest();
            inValue.Body = new ServiceReferenceClient.GetProductListRequestBody();
            return ((ServiceReferenceClient.WebService2Soap)(this)).GetProductListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient.AddProductToShoppingListResponse ServiceReferenceClient.WebService2Soap.AddProductToShoppingList(ServiceReferenceClient.AddProductToShoppingListRequest request)
        {
            return base.Channel.AddProductToShoppingList(request);
        }
        
        public void AddProductToShoppingList(string id)
        {
            ServiceReferenceClient.AddProductToShoppingListRequest inValue = new ServiceReferenceClient.AddProductToShoppingListRequest();
            inValue.Body = new ServiceReferenceClient.AddProductToShoppingListRequestBody();
            inValue.Body.id = id;
            ServiceReferenceClient.AddProductToShoppingListResponse retVal = ((ServiceReferenceClient.WebService2Soap)(this)).AddProductToShoppingList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient.AddProductToShoppingListResponse> ServiceReferenceClient.WebService2Soap.AddProductToShoppingListAsync(ServiceReferenceClient.AddProductToShoppingListRequest request)
        {
            return base.Channel.AddProductToShoppingListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient.AddProductToShoppingListResponse> AddProductToShoppingListAsync(string id)
        {
            ServiceReferenceClient.AddProductToShoppingListRequest inValue = new ServiceReferenceClient.AddProductToShoppingListRequest();
            inValue.Body = new ServiceReferenceClient.AddProductToShoppingListRequestBody();
            inValue.Body.id = id;
            return ((ServiceReferenceClient.WebService2Soap)(this)).AddProductToShoppingListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient.FinishShoppingResponse ServiceReferenceClient.WebService2Soap.FinishShopping(ServiceReferenceClient.FinishShoppingRequest request)
        {
            return base.Channel.FinishShopping(request);
        }
        
        public ServiceReferenceClient.SelectedProduct[] FinishShopping()
        {
            ServiceReferenceClient.FinishShoppingRequest inValue = new ServiceReferenceClient.FinishShoppingRequest();
            inValue.Body = new ServiceReferenceClient.FinishShoppingRequestBody();
            ServiceReferenceClient.FinishShoppingResponse retVal = ((ServiceReferenceClient.WebService2Soap)(this)).FinishShopping(inValue);
            return retVal.Body.FinishShoppingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient.FinishShoppingResponse> ServiceReferenceClient.WebService2Soap.FinishShoppingAsync(ServiceReferenceClient.FinishShoppingRequest request)
        {
            return base.Channel.FinishShoppingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient.FinishShoppingResponse> FinishShoppingAsync()
        {
            ServiceReferenceClient.FinishShoppingRequest inValue = new ServiceReferenceClient.FinishShoppingRequest();
            inValue.Body = new ServiceReferenceClient.FinishShoppingRequestBody();
            return ((ServiceReferenceClient.WebService2Soap)(this)).FinishShoppingAsync(inValue);
        }
        
        public double GetAccount()
        {
            return base.Channel.GetAccount();
        }
        
        public System.Threading.Tasks.Task<double> GetAccountAsync()
        {
            return base.Channel.GetAccountAsync();
        }
        
        public int GetNum()
        {
            return base.Channel.GetNum();
        }
        
        public System.Threading.Tasks.Task<int> GetNumAsync()
        {
            return base.Channel.GetNumAsync();
        }
        
        public void ClearShoppingList()
        {
            base.Channel.ClearShoppingList();
        }
        
        public System.Threading.Tasks.Task ClearShoppingListAsync()
        {
            return base.Channel.ClearShoppingListAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient.ShowSelectedProductsResponse ServiceReferenceClient.WebService2Soap.ShowSelectedProducts(ServiceReferenceClient.ShowSelectedProductsRequest request)
        {
            return base.Channel.ShowSelectedProducts(request);
        }
        
        public ServiceReferenceClient.SelectedProduct[] ShowSelectedProducts()
        {
            ServiceReferenceClient.ShowSelectedProductsRequest inValue = new ServiceReferenceClient.ShowSelectedProductsRequest();
            inValue.Body = new ServiceReferenceClient.ShowSelectedProductsRequestBody();
            ServiceReferenceClient.ShowSelectedProductsResponse retVal = ((ServiceReferenceClient.WebService2Soap)(this)).ShowSelectedProducts(inValue);
            return retVal.Body.ShowSelectedProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient.ShowSelectedProductsResponse> ServiceReferenceClient.WebService2Soap.ShowSelectedProductsAsync(ServiceReferenceClient.ShowSelectedProductsRequest request)
        {
            return base.Channel.ShowSelectedProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient.ShowSelectedProductsResponse> ShowSelectedProductsAsync()
        {
            ServiceReferenceClient.ShowSelectedProductsRequest inValue = new ServiceReferenceClient.ShowSelectedProductsRequest();
            inValue.Body = new ServiceReferenceClient.ShowSelectedProductsRequestBody();
            return ((ServiceReferenceClient.WebService2Soap)(this)).ShowSelectedProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceClient.RemoveSelectedResponse ServiceReferenceClient.WebService2Soap.RemoveSelected(ServiceReferenceClient.RemoveSelectedRequest request)
        {
            return base.Channel.RemoveSelected(request);
        }
        
        public void RemoveSelected(string id)
        {
            ServiceReferenceClient.RemoveSelectedRequest inValue = new ServiceReferenceClient.RemoveSelectedRequest();
            inValue.Body = new ServiceReferenceClient.RemoveSelectedRequestBody();
            inValue.Body.id = id;
            ServiceReferenceClient.RemoveSelectedResponse retVal = ((ServiceReferenceClient.WebService2Soap)(this)).RemoveSelected(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceClient.RemoveSelectedResponse> ServiceReferenceClient.WebService2Soap.RemoveSelectedAsync(ServiceReferenceClient.RemoveSelectedRequest request)
        {
            return base.Channel.RemoveSelectedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceClient.RemoveSelectedResponse> RemoveSelectedAsync(string id)
        {
            ServiceReferenceClient.RemoveSelectedRequest inValue = new ServiceReferenceClient.RemoveSelectedRequest();
            inValue.Body = new ServiceReferenceClient.RemoveSelectedRequestBody();
            inValue.Body.id = id;
            return ((ServiceReferenceClient.WebService2Soap)(this)).RemoveSelectedAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService2Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService2Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService2Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:65225/WebService2.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService2Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:65225/WebService2.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService2Soap,
            
            WebService2Soap12,
        }
    }
}
